### ISSUE TITLE
eggs information 

### ISSUE THREAD

**Issue by YutingMao1993** [IITIDIDX597/sp_2019_team1#23]
As Users,
I want to be able to see who created the egg,
so that I can have more information.

**Comment by Tombodil** [comment]
As Users,
I want to be able to see who created the egg,
so that I can have more information. (what information and why is it relevant?)

Also sub hill and hill info is needed for each story. Other then needing to make the purpose evident in this story, the language is good.

**Comment by YutingMao1993** [comment]
As Users,
I want to be able to see who created the egg,
so that I can have more information.

Sub-hill: Users can see who created the egg to get more 
information if they want it. 

Part of hill: which will boost the variety of events and the employees' engagement with and ownership of events.

**Comment by akallish** [comment]
@evanwchan @YutingMao1993 this story feels the same as other stories and not sure if it is adding value. Also, you are not using the nomenclature for your project in terms of users. "User" is not specific enough. Below is a take on modifying it:

> As a participant,
> I want to be able to see who created the egg,
> so that I can decide if I want to invest in participating or leading it
> 
**Sub-hill:** Users can see who created the egg to get more
> information if they want it.
> 
**Part of hill:** which will boost the variety of events and the employees' engagement with and ownership of events.

**Comment by evanwchan** [comment]
I agree, Adam. This is basically the same as story #20. Should I simply delete this one then? Closing it out would imply that it's been completed, which obviously isn't what we want to do with this. 

> @evanwchan @YutingMao1993 this story feels the same as other stories and not sure if it is adding value. Also, you are not using the nomenclature for your project in terms of users. "User" is not specific enough. Below is a take on modifying it:
> 
> > As a participant,
> > I want to be able to see who created the egg,
> > so that I can decide if I want to invest in participating or leading it
> 
> **Sub-hill:** Users can see who created the egg to get more
> 
> > information if they want it.
> 
> **Part of hill:** which will boost the variety of events and the employees' engagement with and ownership of events.

**Comment by akallish** [comment]
@evanwchan it is ok to close it
